[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss05"

    [buildPlans.iosevka-custom.variants.design]
    g = "single-storey-serifless"
    ampersand = "upper-open"

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"