name: Manual build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Iosevka version'
        default: '10.1.0'
        required: true

jobs:
  build:
    name: Build font
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: 'custom'

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -y install ttfautohint libttfautohint-dev

    - name: Download Iosevka source
      uses: actions/checkout@v2
      with:
        repository: be5invis/Iosevka
        ref: v${{ github.event.inputs.version }}
        path: 'iosevka'

    - name: Copy build plans
      working-directory: custom
      run: cp private-build-plans.toml ../iosevka

    - name: Install Node dependencies
      working-directory: iosevka
      run: npm install

    - name: Build TTF files
      working-directory: iosevka
      run: npm run build -- ttf::iosevka-custom

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: iosevka-custom-${{ github.event.inputs.version }}
    #     path: iosevka/dist/iosevka-custom/ttf

    - name: Create zip
      working-directory: iosevka/dist/iosevka-custom/ttf
      run: 7z -tzip a iosevka-custom-${{ github.event.inputs.version }}.zip *

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: Iosevka Custom ${{ github.event.inputs.version }}
        draft: true
        prerelease: false

    - name: Upload release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: iosevka/dist/iosevka-custom/ttf/iosevka-custom-${{ github.event.inputs.version }}.zip
        asset_name: iosevka-custom-${{ github.event.inputs.version }}.zip
        asset_content_type: application/zip