# This is a basic workflow that is manually triggered

name: Manual build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'version'
        description: 'Iosevka version'
        # Default value if no value is explicitly provided
        default: '3.4.6'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build font
    # The type of runner that the job will run on
    runs-on: windows-latest
    # env:
      # otfcc:

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    # TODO: Cache ttfautohint
    - name: Install ttfautohint
      run: |
        curl -LO https://phoenixnap.dl.sourceforge.net/project/freetype/ttfautohint/1.8.3/ttfautohint-1.8.3-win32.7z
        7z e ttfautohint-1.8.3-win32.7z ttfautohint.exe
        echo "::add-path::./ttfautohint.exe"
    # TODO: Cache otfcc
    - name: Install otfcc
      run: |
        curl -LO https://github.com/caryll/otfcc/releases/download/v0.10.4/otfcc-win64-0.10.4.zip
        7z e otfcc-win64-0.10.4.zip
        echo "::add-path::./otfccbuild.exe"
        echo "::add-path::./otfccdump.exe"
    - name: Download Iosevka source
      run: |
        curl -LO "https://github.com/be5invis/Iosevka/archive/v${{ github.event.inputs.version }}.zip"
      # 7z e ttfautohint-1.8.3-win32.7z ttfautohint.exe
    - name: Debug current location again
      run: |
        cd
        dir
    - name: Install Python dependencies
      run: |
        pip install afdko
    # - name: Install Node dependencies
    #   run: |
    #     npm install
    # - name: Execute build
    #   run: npm run build -- ttf::iosevka-custom
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: iosevka-custom-${{ github.event.inputs.version }}
    #     path: |
    #       path/output/bin/
    #       path/output/test-results
    #       !path/**/*.tmp